version: '3.8'

services:
  ezlinkai:
    image: ye4293xx7/one-api:latest
    container_name: ezlinkai2
    restart: always
    command: --log-dir /app/logs
    ports:
      - "5001:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      - SQL_DSN=missai:rze@rV53e4BDwyj@tcp(ezlinkai.rwlb.rds-aliyun-america.rds.aliyuncs.com:3306)/ezlinkai2
      - REDIS_CONN_STRING=rediss://ezlink-cache-user-1:sina*9Fgk@k7a8fs@ezlink-pgifdn.serverless.usw1.cache.amazonaws.com:6379
      - SYNC_FREQUENCY=120
      - BATCH_UPDATE_ENABLED=true
      - MEMORY_CACHE_ENABLED=true
      - BATCH_UPDATE_INTERVAL=5
      - SQL_MAX_IDLE_CONNS=50
      - SQL_MAX_OPEN_CONNS=300
      - SQL_MAX_LIFETIME=1800
      - RELAY_TIMEOUT=1800
      - STREAMING_TIMEOUT=600
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s